# Generated by Django 5.1.1 on 2024-10-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_fan_lesson_date_fan_juftmi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson_date',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='pupilNumber',
            field=models.IntegerField(default=0),
        ),
    ]
